version: 2.1

jobs:
  hello:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: medium
    steps:
      - run: echo "hello world" # run the `echo` command
  fetch-code-and-run:
    docker: 
      - image: cimg/aws:2023.03
    resource_class: small
    steps:
      - checkout # check out the code in the project directory
      - run: |
          ls -la;
          make data;

          aws --version;
          aws s3 ls;
          
          echo Here are all the stacks:
          aws cloudformation list-stacks;
          
          echo Creating a stack
          aws cloudformation create-stack --stack-name myteststack \
          --template-body file://iac/cfn/s3_bucket.yaml \
          --parameters ParameterKey=ProjectName,ParameterValue=S3BucketStack \
          ParameterKey=BucketName,ParameterValue=circle-ci-test-990 \
          ParameterKey=DataLayer,ParameterValue=Raw \
          ParameterKey=Environment,ParameterValue=Dev \
          --region us-east-1

workflows:
  my-workflow:
    jobs:
      - hello
      - fetch-code-and-run:
          requires: 
            - hello
