version: 2.1

jobs:
  hello:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: medium
    steps:
      - run: echo "hello world" # run the `echo` command
  fetch-code-and-run:
    docker: 
      - image: cimg/aws:2023.03
    resource_class: small
    steps:
      - checkout # check out the code in the project directory
      - run: |
          echo In a container which has aws cli. This will allow for commands to be executed in the aws cloud;
          aws --version;
          aws s3 ls --profile ${AWS_PROFILE};
          aws s3 ls;
          ls -la;
          make data;

workflows:
  my-workflow:
    jobs:
      - hello
      - fetch-code-and-run:
          requires: 
            - hello
