version: 2.1

executors:
  my-executor:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: medium
    working_directory: ~/workspace

commands:
  run_some_code:
    steps:
      - run:
          name: Running some code
          command: | 
            echo hi
            #git clone https://github.com/Snowflake-Labs/schemachange.git
            #pip install -r schemachange/requirements.txt
            #python schemachange/cli.py -h

jobs:
  fetch-code:
    description: Checkout codebase
    # machine:
    #   image: ubuntu-2204:2022.07.1
    # resource_class: medium
    executor: my-executor
    steps:
      - run: pwd; ls -la
      - checkout # check out the code in the project directory
      - run: pwd; ls -la
      # - run: cp ./* ~/workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - ./

  
  build-code:
    description: building the codebase and running through the test cases
    # machine:
    #   image: ubuntu-2204:2022.07.1
    # resource_class: medium
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: pwd; cd ~/workspace/; ls -la
      - run_some_code
      - run: 
          name: clean, lint, and scan codebase
          command: echo "clean, lint, and performing static scans against the codebase" # check out the code in the project directory
      - run:
          name: build codebase
          command: echo building the codebase
      - run:
          name: test codebase
          command: echo unit testing and code coverage of the build

  deploy-dev:
    docker: 
      - image: cimg/aws:2023.03
    resource_class: small
    steps:
      - checkout
      - run_some_code
      - run: echo deploying the codebase to the dev env
      # - run: |
      #     ls -la;
      #     make lint data;
      #     aws --version;
      #     aws s3 ls;
          
      #     echo Here are all the stacks:
      #     aws cloudformation list-stacks;
          
      #     echo Creating a stack --region us-east-1
      #     aws cloudformation create-stack --stack-name myteststack \
      #     --template-body file://iac/cfn/s3_bucket.yaml \
      #     --parameters ParameterKey=ProjectName,ParameterValue=S3BucketStack \
      #     ParameterKey=BucketName,ParameterValue=circle-ci-test-990 \
      #     ParameterKey=DataLayer,ParameterValue=Raw \
      #     ParameterKey=Environment,ParameterValue=Dev \
      #     --region us-east-1

  deploy-uat:
    docker: 
      - image: cimg/aws:2023.03
    resource_class: small
    steps:
      - run: echo deploying the codebase to the uat env

  deploy-prod:
    docker: 
      - image: cimg/aws:2023.03
    resource_class: small
    steps:
      - run: echo deploying the codebase to the prod env

workflows:
  my-workflow:
    jobs:
      - fetch-code
      - build-code:
          requires: 
              - fetch-code
      - deploy-dev:
          requires:
              - build-code
          filters:
            branches:
              only: develop
      - deploy-to-uat:
          type: approval
          requires:
            - deploy-dev
      - deploy-uat:
          requires:
            - deploy-to-uat
          filters:
            branches:
              only: release
      - deploy-to-prod:
          type: approval
          requires:
            - deploy-uat
      - deploy-prod:
          requires: 
            - deploy-to-prod
