version: 2.1

executors:
  my-executor:
    docker:
      # - image: cimg/python:3.11.2
      - image: cimg/aws:2023.03
    resource_class: medium
    working_directory: ~/workspace

commands:
  install_python:
    steps:
      - run:
          name: install python in environment
          command: |
            sudo apt-get update
            sudo apt-get install python3.11
  create_virtual_env:
    steps:
      - run:
          name: create a virual environment
          command: |
            python3 -m pip install --upgrade pip
            python3 -m pip install --user virtualenv
            virtualenv venv
            source venv/bin/activate
  get_schema_change_repo:
    steps:
      - run:
          name: getting schemachange repo
          command: | 
            git clone https://github.com/Snowflake-Labs/schemachange.git --depth=1
            python3 -m pip install numpy requests Jinja2 pandas PyYAML snowflake-connector-python
            # python3 -m pip install -r schemachange/requirements.txt # does not work.. have to remove the versions in the file
            ls -la schemachange
            python3 schemachange/schemachange/cli.py -h

jobs:
  fetch-code:
    description: Checkout codebase
    # machine:
    #   image: ubuntu-2204:2022.07.1
    # resource_class: medium
    executor: my-executor
    steps:
      - checkout # check out the code in the project directory
      - install_python
      - create_virtual_env
      - get_schema_change_repo
      - run: pwd; ls -la
      - run: pip freeze >> packages_installed.txt | tee -a
      # - save_cache:
      #     key: deps-{{ checksum "packages_installed.txt" }}
      #     paths: 
      #       - ./
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  build-code:
    description: building the codebase and running through the test cases
    # machine:
    #   image: ubuntu-2204:2022.07.1
    # resource_class: medium
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: pwd; ls -la
      - run: 
          name: clean, lint, and scan codebase
          command: echo "clean, lint, and performing static scans against the codebase" # check out the code in the project directory
      - run:
          name: build codebase
          command: echo building the codebase
      - run:
          name: test codebase
          command: echo unit testing and code coverage of the build

  deploy-dev:
    # docker: 
    #   - image: cimg/aws:2023.03
    # resource_class: small
    executor: my-executor
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: pwd; ls -la; ls -la venv; ls -la venv/bin
      - run: source venv/bin/activate
      - run: pwd; ls -la
      - run: pip freeze
      - run: echo deploying the codebase to the dev env
      - run: |
            SNOWFLAKE_AUTHENTICATOR=externalbrowser \
            python3 schemachange/schemachange/cli.py \
            -f ./databases/snowflake/migrations \
            -a ${SNOWFLAKE_ACCOUNT} \
            -u ${SNOWFLAKE_USER} \
            -r ${SNOWFLAKE_ROLE} \
            -w ${SNOWFLAKE_WAREHOUSE} \
            -d ${SNOWFLAKE_DATABASE} \
            -c ${SNOWFLAKE_DATABASE}.${SNOWFLAKE_SCHEMA}.CHANGE_HISTORY \
            --query-tag DATA_ENGINEERING \
            --vars "{\"DB\": \"${SNOWFLAKE_DATABASE}\", \"SCHEMA\": \"${SNOWFLAKE_SCHEMA}\" }" \
            -v
      # - run: |
      #     ls -la;
      #     make lint data;
      #     aws --version;
      #     aws s3 ls;
          
      #     echo Here are all the stacks:
      #     aws cloudformation list-stacks;
          
      #     echo Creating a stack --region us-east-1
      #     aws cloudformation create-stack --stack-name myteststack \
      #     --template-body file://iac/cfn/s3_bucket.yaml \
      #     --parameters ParameterKey=ProjectName,ParameterValue=S3BucketStack \
      #     ParameterKey=BucketName,ParameterValue=circle-ci-test-990 \
      #     ParameterKey=DataLayer,ParameterValue=Raw \
      #     ParameterKey=Environment,ParameterValue=Dev \
      #     --region us-east-1

  deploy-uat:
    docker: 
      - image: cimg/aws:2023.03
    resource_class: small
    steps:
      - run: echo deploying the codebase to the uat env

  deploy-prod:
    docker: 
      - image: cimg/aws:2023.03
    resource_class: small
    steps:
      - run: echo deploying the codebase to the prod env

workflows:
  my-workflow:
    jobs:
      - fetch-code
      - build-code:
          requires: 
              - fetch-code
      - deploy-dev:
          requires:
              - build-code
          # filters:
          #   branches:
          #     only: develop
      - deploy-to-uat:
          type: approval
          requires:
            - deploy-dev
      - deploy-uat:
          requires:
            - deploy-to-uat
          filters:
            branches:
              only: release
      - deploy-to-prod:
          type: approval
          requires:
            - deploy-uat
      - deploy-prod:
          requires: 
            - deploy-to-prod
