Parameters:
  ProjectName:
    Type: String
    Description: "Project name"
    Default: "arch_prj"
  DataLayer:
    Type: String
    AllowedValues:
      - Raw
      - Curated
    Description: "Select a data layer"
  Environment:
    Type: String
    AllowedValues:
      - Dev
      - Uat
      - Prod
    Description: "Select an environment"

Mappings:
  EnvironmentToBucketSuffix:
    Dev:
      Suffix: "dev"
    Uat:
      Suffix: "uat"
    Prod:
      Suffix: "prod"
  DataLayerToBucketSuffix:
    Raw:
      Suffix: "raw"
    Curated:
      Suffix: "curated"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [ "fluidmachine",
          !FindInMap [
            DataLayerToBucketSuffix,
            !Ref DataLayer,
            Suffix
          ],
          !FindInMap [
            EnvironmentToBucketSuffix,
            !Ref Environment,
            Suffix
          ],
          !Select [0, !Split [-, !Select [2, !Split [/, !Ref AWS::StackId ]]]]
        ]
      ]
      Tags:
        - Key: env
          Value: !Ref Environment
        - Key: proj
          Value: !Ref ProjectName

Outputs:
  BucketName:
    Description: Name of bucket
    Value: !Ref S3Bucket
