AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProjectName:
    Type: String
    Description: 'Project name'
    Default: 'arch_prj'
  Environment:
    Type: String
    Description: 'Select an environment'
    AllowedValues:
      - dev
      - uat
      - prod
  SnowflakeUsername:
    Type: String
    Description: 'Snowflake Username'
  SnowflakePassword:
    Type: String
    Description: 'Snowflake Password'
  SnowflakeAccount:
    Type: String
    Description: 'Snowflake Account'
  MatillionAuthToken:
    Type: String
    Description: 'Matillion Auth Token'

Resources:
  SnowflakeSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Join [ '/', [ !Ref Environment, "snowflake" ] ]
      Description: "Snowflake connection secret"
      SecretString: !Sub
        - '{"username" : "${username}", "password" : "${password}, "account" : "${account}"}'
        - username: !Ref SnowflakeUsername
          password: !Ref SnowflakePassword
          account:  !Ref SnowflakeAccount
      Tags:
        - Key: Project Name
          Value: !Ref ProjectName

  MatillionSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Join [ '/', [ !Ref Environment, "matillion" ] ]
      Description: "Matillion secret to connect to the REST Api"
      SecretString: !Sub
        - '{"auth_token" : "${AuthToken}"}'
        - AuthToken: !Ref MatillionAuthToken
      Tags:
        - Key: Project Name
          Value: !Ref ProjectName
